<!DOCTYPE html>
<html lang="ru" ng-app="TempList">
    <head>
        <meta charset="utf-8">
        <title>List Post</title>
        <link rel="stylesheet" href="libs/dist/css/bootstrap.min.css"/>
        <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" href="style.css"/>
        <style>
            body {
                padding-top: 40px;
                padding-bottom: 40px;
                background-color: #eee;
            }

            .form-signin {
                max-width: 330px;
                padding: 15px;
                margin: 0 auto;
            }
            .form-signin .form-signin-heading,
            .form-signin .checkbox {
                margin-bottom: 10px;
            }
            .form-signin .checkbox {
                font-weight: normal;
            }
            .form-signin .form-control {
                position: relative;
                height: auto;
                -webkit-box-sizing: border-box;
                -moz-box-sizing: border-box;
                box-sizing: border-box;
                padding: 10px;
                font-size: 16px;
            }
            .form-signin .form-control:focus {
                z-index: 2;
            }
            .form-signin input[type="email"] {
                margin-bottom: -1px;
                border-bottom-right-radius: 0;
                border-bottom-left-radius: 0;
            }
            .form-signin input[type="password"] {
                margin-bottom: 10px;
                border-top-left-radius: 0;
                border-top-right-radius: 0;
            }
        </style>
    </head>
    <body role="document" ng-controller="MainCtrl">


        <div class="container">

            <form class="form-signin" action="/signup/login" method="post">
                <h3><b>MEDIUS </b><small>АРМ медсестры</small></h3>
                <h4 class="form-signin-heading">Пожалуйста авторизируйтесь</h4>
                <label for="login" class="sr-only">Логин</label>
                <input type="text" class="form-control" name="login" placeholder="логин" required/><br/>
                <label for="inputPassword" class="sr-only">Пароль</label>
                <input type="password" class="form-control" placeholder="пароль" name="password" required/><br/>
                <input type="submit" class="btn btn-primary" value="Вход"/>
            </form>
        </div>

        <script src="libs/jquery.min.js"></script>
        <script src="libs/angular.min.js"></script>
        <script src="libs/bootstrap.min.js"></script>
        <script src="libs/angular-cookies.min.js"></script>
        <script src="app.js"></script>
        <script src="controllers/DataController.js"></script>
        <script src="services/RenderChartsService.js"></script>
        <script src="factories/PatientFactory.js"></script>
        <script src="factories/DataFactory.js"></script>
        <script src="services/RetrieveService.js"></script>
    </body>
</html>