<!DOCTYPE html>

<html lang="ru" ng-app="TempList">
    <head>
        <meta charset="utf-8">
        <title>List Post</title>
        <link rel="stylesheet" href="libs/dist/css/bootstrap.min.css"/>
        <link rel="stylesheet" href="style.css"/>
    </head>
    <body role="document" ng-controller="MainCtrl">

        <!-- Fixed navbar -->
        <nav class="navbar navbar-default" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="http://localhost/temparaturelist/">List Post</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="" ng-click="showAddForm()"> <i class="glyphicon glyphicon-plus-sign"></i> Добавить лист</a></li>
                        <li><a href="" ng-click="showingPanels()"><i class="glyphicon glyphicon-user"></i> Список пациентов</a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>


        <div class="container">
            <div class="row">
                <div class="col-sm-3">
                    <!--Форма для добавления пациента-->
                    <div ng-show="showingAddPatient">
                        <form name="form">
                            <label>Имя</label><br/>
                            <input type="text" placeholder="Введите имя пациента" ng-model="name" name="name" class="form-control"/><br/>
                            <button ng-click="cancelPatientForm()" type="button" class="btn btn-sm btn-danger"><i class="glyphicon glyphicon-remove"></i> Отмена</button>
                            <button ng-click="sendPatient()" name="send" class="btn btn-sm btn-primary"><i class="glyphicon glyphicon-save"></i> Сохранить</button>
                        </form>
                        <hr>
                    </div>
                    <!--#Форма для добавления пациента-->
                    <!--Поиск по пациентам-->
                    <input type="search" placeholder="Поиск" class="form-control" ng-model="search"/>
                    <!--#Поиск по пациентам-->
                    <hr>
                    <!--Список пациентов-->
                    <div class="patient-block" ng-repeat="patient in names | filter:search | orderBy:'name'" ng-click="selectedPatient(patient)">
                        <a style="text-decoration: none;" href="" ng-bind="patient.name"></a>
                    </div>
                    <!--#Список пациентов-->
                </div>
                <div class="col-sm-9" ng-controller="DataCtrl">
                    <div ng-include="'templates/listpatient.html'">                 
                    </div>
                    <div id="charts-block" ng-show="showPanels">
                        <!--Владки с температурой, давлением, пульсом-->
                        <tabset justified="true">
                            <tab heading="Температура">
                                <div ng-cloak id="container-temperature" style="min-width: 820px;  height: 400px; "></div>
                            </tab>
                            <tab heading="Пульс">
                                <div ng-cloak id="container-pulse" style="min-width: 820px; height: 400px; "></div>
                            </tab>
                            <tab heading="Давление">
                                <div ng-cloak id="container-pressure" style="min-width: 820px;  height: 400px;"></div>
                            </tab>
                            <tab heading="Данные">
                                <div ng-cloak ng-include="'templates/temperature.html'">
                                </div>
                                <div ng-cloak ng-include="'templates/pulse.html'">
                                </div>
                                <div ng-cloak ng-include="'templates/pressure.html'">
                                </div>
                            </tab>
                        </tabset>
                        <!--#Владки с температурой, давлением, пульсом-->
                    </div>
                </div>
            </div>
        </div>



        <script src="libs/jquery.min.js"></script>
        <script src="libs/angular.min.js"></script>
        <script src="libs/highcharts/js/highcharts.js"></script>
        <script src="http://code.highcharts.com/modules/exporting.js"></script>
        <script src="libs/ui-bootstrap.min.js"></script>
        <script src="app.js"></script>
        <script src="services/RenderChartsService.js"></script>
        <script src="factories/PatientFactory.js"></script>
        <script src="factories/DataFactory.js"></script>
        <script src="services/RetrieveService.js"></script>
    </body>
</html>