<!DOCTYPE html>

<html lang="ru" ng-app="TempList">
    <head>
        <meta charset="utf-8">
        <title>List Post</title>
        <link rel="stylesheet" href="libs/dist/css/bootstrap.min.css"/>
        <link rel="stylesheet" href="libs/dist/css/bs.bootstrap.min.css"/>
        <link rel="stylesheet" href="style.css"/>
    </head>
    <body role="document" ng-controller="MainCtrl">

        <!-- Fixed navbar -->
        <nav class="navbar navbar-default" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="" ng-click="reload()">List Post</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="" ng-click="showAddForm()"> <i class="glyphicon glyphicon-plus-sign"></i> Добавить лист</a></li>
                        <li><a href="" ng-click="showingPanels()"><i class="glyphicon glyphicon-user"></i> Список пациентов</a></li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="" id="login"><?php echo $loginUser;?></a></li>
                        <input type="hidden" id="iduser" value="<?php echo $idUser;?>">
                        <li><a href="signup/logout" id="login"><i class="glyphicon glyphicon-log-out"></i> Выход</a></li>
                    </ul>

                </div><!--/.nav-collapse -->
            </div>
        </nav>


        <div class="maincontainer">
            <div class="row">
                <div class="col-sm-3">
                    <!--Форма для добавления пациента-->
                    <div ng-show="showingAddPatient">
                        <form name="form">
                            <label>Карточка</label><br/>
                            <input type="text" placeholder="Введите номер карты" ng-model="card" name="card" class="form-control"/><br/>
                            <label>Имя</label><br/>
                            <input type="text" placeholder="Введите имя пациента" ng-model="name" name="name" class="form-control"/><br/>
                            <button ng-click="cancelPatientForm(); card=null; name=null" type="button" class="btn btn-sm btn-danger"><i class="glyphicon glyphicon-remove"></i> Отмена</button>
                            <button ng-click="sendPatient()" name="send" class="btn btn-sm btn-primary"><i class="glyphicon glyphicon-save"></i> Сохранить</button>
                        </form>
                        <hr>
                    </div>
                    <!--#Форма для добавления пациента-->
                    <!--Поиск по пациентам-->
                    <input type="search" placeholder="Поиск" class="form-control" ng-model="search"/>
                    <!--#Поиск по пациентам-->
                    <hr>
                    <!--Список пациентов-->
                    <div class="patient-block" ng-repeat="patient in names | filter:search | orderBy:'name'" ng-class="{
                                sel: $index == selected
                            }" ng-click="selectedPatient(patient);
                                    addActive($index)">
                        <a style="text-decoration: none;" href="" >{{patient.name}} {{patient.card}}</a>
                    </div>
                    <!--#Список пациентов-->
                </div>
                <div class="col-sm-9" ng-controller="DataCtrl">

                    <div class="info" ng-show="info">
                        <div ng-include="'templates/info.html'">                 
                        </div>
                    </div>
                    <div class="data" ng-hide="info">
                        <div ng-include="'templates/listpatient.html'">                 
                        </div>
                        <div id="charts-block" ng-show="showPanels">
                            <!--Владки с температурой, давлением, пульсом-->

                            <div role="tabpanel">

                                <!-- Nav tabs -->
                                <ul class="nav nav-tabs" role="tablist">
                                    <li role="presentation" class="active"><a href="#temperature" aria-controls="temperature" role="tab" data-toggle="tab">Температура</a></li>
                                    <li role="presentation"><a href="#pulse" aria-controls="pulse" role="tab" data-toggle="tab">Пульс</a></li>
                                    <li role="presentation"><a href="#pressure" aria-controls="pressure" role="tab" data-toggle="tab">Давление</a></li>
                                    <li role="presentation"><a href="#datas" aria-controls="datas" role="tab" data-toggle="tab">Данные</a></li>
                                </ul>

                                <!-- Tab panes -->
                                <div class="tab-content">
                                    <div role="tabpanel" class="tab-pane active" id="temperature">
                                        <div ng-cloak id="container-temperature" style="min-width: 820px;  height: 400px; "></div>
                                    </div>
                                    <div role="tabpanel" class="tab-pane" id="pulse">
                                        <div ng-cloak id="container-pulse" style="min-width: 820px; height: 400px; "></div>
                                    </div>
                                    <div role="tabpanel" class="tab-pane" id="pressure">
                                        <div ng-cloak id="container-pressure" style="min-width: 820px;  height: 400px;"></div>
                                    </div>
                                    <div role="tabpanel" class="tab-pane" id="datas">
                                        <div ng-cloak ng-include="'templates/temperature.html'">
                                        </div>
                                        <div ng-cloak ng-include="'templates/pulse.html'">
                                        </div>
                                        <div ng-cloak ng-include="'templates/pressure.html'">
                                        </div>
                                    </div>
                                </div>

                            </div>

<!--                            <tabset justified="true">
                                <tab heading="Температура">
                                    <div ng-cloak id="container-temperature" style="min-width: 820px;  height: 400px; "></div>
                                </tab>
                                <tab heading="Пульс">
                                    <div ng-cloak id="container-pulse" style="min-width: 820px; height: 400px; "></div>
                                </tab>
                                <tab heading="Давление">
                                    <div ng-cloak id="container-pressure" style="min-width: 820px;  height: 400px;"></div>
                                </tab>
                                <tab heading="Данные">
                                    <div ng-cloak ng-include="'templates/temperature.html'">
                                    </div>
                                    <div ng-cloak ng-include="'templates/pulse.html'">
                                    </div>
                                    <div ng-cloak ng-include="'templates/pressure.html'">
                                    </div>
                                </tab>
                            </tabset>-->
                            <!--#Владки с температурой, давлением, пульсом-->
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <script src="libs/jquery.min.js"></script>
        <script src="libs/angular.min.js"></script>
        <script src="libs/highcharts/js/highcharts.js"></script>
        <script src="libs/angular-cookies.min.js"></script>
        <script src="http://code.highcharts.com/modules/exporting.js"></script>
        <script src=""></script>
        <!--<script src="libs/ui-bootstrap.min.js"></script>-->
        <script src="libs/bootstrap.min.js"></script>
        <script src="app.js"></script>
        <script src="controllers/DataController.js"></script>
        <script src="services/RenderChartsService.js"></script>
        <script src="factories/PatientFactory.js"></script>
        <script src="factories/DataFactory.js"></script>
        <script src="services/RetrieveService.js"></script>
    </body>
</html>